package view;

import controller.Conversor;
import java.awt.FileDialog;
import java.io.File;
import java.io.FilenameFilter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.RelacaoCsvBib;

/**
 *
 * @author Jônatas Trabuco Belotti [jonatas.t.belotti@hotmail.com]
 */
public class TelaPrincipal extends javax.swing.JFrame {

    private FileDialog janelaAbrir;
    private FileDialog janelaSalvar;
    private String caminhoAbrirArquivos;
    private List<String> nomesAbrirArquivos;
    private String caminhoSalvarArquivo;
    private String nomeSalvarArquivo;
    private DefaultTableModel modeloTabela;
    private Conversor conversor;

    public TelaPrincipal() {
        initComponents();
        modeloTabela = (DefaultTableModel) jTbRelacaoNomes.getModel();
        this.conversor = new Conversor();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPnEtapa1 = new javax.swing.JPanel();
        jTxtLocalArbirArquivos = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLbQuantidadeArquivos = new javax.swing.JLabel();
        jLbNomesArquivos = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPnEtapa3 = new javax.swing.JPanel();
        jTxtLocalSalvarArquivo = new javax.swing.JTextField();
        jBtnSalvar = new javax.swing.JButton();
        jLbEtapa3 = new javax.swing.JLabel();
        jLbEtapa3Desc = new javax.swing.JLabel();
        jPnEtapa2 = new javax.swing.JPanel();
        jLbEtapa2 = new javax.swing.JLabel();
        jLbEtapa2Desc = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTbRelacaoNomes = new javax.swing.JTable();
        jPnEtapa4 = new javax.swing.JPanel();
        jBtnConverter = new javax.swing.JButton();
        jLbEtapa4 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Convert csv in bibTex");
        setResizable(false);

        jPnEtapa1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jTxtLocalArbirArquivos.setText("Selecione os arquivos para converter");
        jTxtLocalArbirArquivos.setEnabled(false);

        jButton1.setText("Abrir");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setText("Etapa 1");

        jLabel3.setText("Total:");

        jLbQuantidadeArquivos.setText("0");

        jLbNomesArquivos.setText("Arquivo1.svg, Arquivo2.svg");

        jLabel6.setText("Selecione os arquivos à serem convertidos:");

        javax.swing.GroupLayout jPnEtapa1Layout = new javax.swing.GroupLayout(jPnEtapa1);
        jPnEtapa1.setLayout(jPnEtapa1Layout);
        jPnEtapa1Layout.setHorizontalGroup(
            jPnEtapa1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnEtapa1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPnEtapa1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPnEtapa1Layout.createSequentialGroup()
                        .addGroup(jPnEtapa1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel6))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPnEtapa1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(jPnEtapa1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPnEtapa1Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLbQuantidadeArquivos))
                            .addGroup(jPnEtapa1Layout.createSequentialGroup()
                                .addComponent(jTxtLocalArbirArquivos)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLbNomesArquivos, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        jPnEtapa1Layout.setVerticalGroup(
            jPnEtapa1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnEtapa1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPnEtapa1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTxtLocalArbirArquivos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPnEtapa1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLbQuantidadeArquivos))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLbNomesArquivos)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPnEtapa3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPnEtapa3.setFocusable(false);

        jTxtLocalSalvarArquivo.setText("Selecione onde salvar o resultado");
        jTxtLocalSalvarArquivo.setEnabled(false);

        jBtnSalvar.setText("Salvar");
        jBtnSalvar.setEnabled(false);
        jBtnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnSalvarActionPerformed(evt);
            }
        });

        jLbEtapa3.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLbEtapa3.setText("Etapa 3");
        jLbEtapa3.setEnabled(false);

        jLbEtapa3Desc.setText("Selecione onde o resultado será salvo:");
        jLbEtapa3Desc.setEnabled(false);

        javax.swing.GroupLayout jPnEtapa3Layout = new javax.swing.GroupLayout(jPnEtapa3);
        jPnEtapa3.setLayout(jPnEtapa3Layout);
        jPnEtapa3Layout.setHorizontalGroup(
            jPnEtapa3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnEtapa3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPnEtapa3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPnEtapa3Layout.createSequentialGroup()
                        .addGroup(jPnEtapa3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPnEtapa3Layout.createSequentialGroup()
                                .addComponent(jLbEtapa3Desc)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPnEtapa3Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jTxtLocalSalvarArquivo)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBtnSalvar))
                    .addGroup(jPnEtapa3Layout.createSequentialGroup()
                        .addComponent(jLbEtapa3)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPnEtapa3Layout.setVerticalGroup(
            jPnEtapa3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnEtapa3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLbEtapa3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLbEtapa3Desc)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPnEtapa3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTxtLocalSalvarArquivo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtnSalvar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPnEtapa2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLbEtapa2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLbEtapa2.setText("Etapa 2");
        jLbEtapa2.setEnabled(false);

        jLbEtapa2Desc.setText("Relacione os campos dos arquivos CSV com os nomes dos campos no arquivo BIBTEX:");
        jLbEtapa2Desc.setEnabled(false);

        jTbRelacaoNomes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Campo no CSV", "Campo no BIBTEX"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTbRelacaoNomes.setEnabled(false);
        jScrollPane1.setViewportView(jTbRelacaoNomes);
        if (jTbRelacaoNomes.getColumnModel().getColumnCount() > 0) {
            jTbRelacaoNomes.getColumnModel().getColumn(0).setResizable(false);
            jTbRelacaoNomes.getColumnModel().getColumn(1).setResizable(false);
        }

        javax.swing.GroupLayout jPnEtapa2Layout = new javax.swing.GroupLayout(jPnEtapa2);
        jPnEtapa2.setLayout(jPnEtapa2Layout);
        jPnEtapa2Layout.setHorizontalGroup(
            jPnEtapa2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnEtapa2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPnEtapa2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLbEtapa2)
                    .addComponent(jLbEtapa2Desc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPnEtapa2Layout.setVerticalGroup(
            jPnEtapa2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnEtapa2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLbEtapa2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLbEtapa2Desc)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPnEtapa4.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jBtnConverter.setText("Converter");
        jBtnConverter.setEnabled(false);
        jBtnConverter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnConverterActionPerformed(evt);
            }
        });

        jLbEtapa4.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLbEtapa4.setText("Etapa 4");
        jLbEtapa4.setEnabled(false);

        javax.swing.GroupLayout jPnEtapa4Layout = new javax.swing.GroupLayout(jPnEtapa4);
        jPnEtapa4.setLayout(jPnEtapa4Layout);
        jPnEtapa4Layout.setHorizontalGroup(
            jPnEtapa4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnEtapa4Layout.createSequentialGroup()
                .addGroup(jPnEtapa4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPnEtapa4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLbEtapa4))
                    .addGroup(jPnEtapa4Layout.createSequentialGroup()
                        .addGap(192, 192, 192)
                        .addComponent(jBtnConverter)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPnEtapa4Layout.setVerticalGroup(
            jPnEtapa4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnEtapa4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLbEtapa4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBtnConverter)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Criado por Jônatas Trabuco Belotti");

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("jonatas.t.belotti@hotmail.com");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPnEtapa1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPnEtapa2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPnEtapa4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPnEtapa3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPnEtapa1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPnEtapa2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPnEtapa3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPnEtapa4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String nomes;

        if (this.janelaAbrir == null) {
            this.janelaAbrir = new FileDialog((java.awt.Frame) null, "Selecionar arquivos", FileDialog.LOAD);
        }

        FilenameFilter filtro = new FilenameFilter() {
            @Override
            public boolean accept(File arquivo, String nome) {
                return nome.toUpperCase().endsWith(".CSV");
            }
        };

        this.janelaAbrir.setMultipleMode(true);
        this.janelaAbrir.setFilenameFilter(filtro);

        this.janelaAbrir.setVisible(true);
        this.caminhoAbrirArquivos = this.janelaAbrir.getDirectory();
        this.nomesAbrirArquivos = new ArrayList();
        for (int i = 0; i < this.janelaAbrir.getFiles().length; i++) {
            if (this.janelaAbrir.getFiles()[i].getName().toUpperCase().endsWith(".CSV")) {
                this.nomesAbrirArquivos.add(this.janelaAbrir.getFiles()[i].getName());
            }
        }

        if (this.caminhoAbrirArquivos != null && this.nomesAbrirArquivos.size() > 0) {
            jTxtLocalArbirArquivos.setText(this.caminhoAbrirArquivos);

            nomes = this.nomesAbrirArquivos.get(0);

            for (int i = 1; i < this.nomesAbrirArquivos.size(); i++) {
                nomes += ", " + this.nomesAbrirArquivos.get(i);
            }

            try {
                this.popularTabela(conversor.identificarNomes(this.caminhoAbrirArquivos, this.nomesAbrirArquivos));
            } catch (IOException ex) {
                Logger.getLogger(TelaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
            }

            this.jLbNomesArquivos.setText(nomes);
            this.jLbQuantidadeArquivos.setText("" + this.nomesAbrirArquivos.size() + "");
            habilitarEtapa2();
            habilitarEtapa3();
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jBtnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnSalvarActionPerformed
        if (this.janelaSalvar == null) {
            this.janelaSalvar = new FileDialog(this, "Salvar arquivo", FileDialog.SAVE);
        }

        this.janelaSalvar.setVisible(true);

        caminhoSalvarArquivo = this.janelaSalvar.getDirectory();
        nomeSalvarArquivo = this.janelaSalvar.getFile();

        if (caminhoSalvarArquivo != null && nomeSalvarArquivo != null) {
            if (nomeSalvarArquivo.indexOf(".") == -1) {
                nomeSalvarArquivo += ".bib";
            }

            jTxtLocalSalvarArquivo.setText(caminhoSalvarArquivo + nomeSalvarArquivo);
            habilitarEtapa4();
        }
    }//GEN-LAST:event_jBtnSalvarActionPerformed

    private void jBtnConverterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnConverterActionPerformed
        List<RelacaoCsvBib> lista = new ArrayList<>();
        
        for (int i = 0; i < this.modeloTabela.getRowCount(); i++) {
            lista.add(new RelacaoCsvBib(modeloTabela.getValueAt(i, 0).toString(), modeloTabela.getValueAt(i, 1).toString()));
        }
        
        conversor.setIdentificadoresRelacionados(lista);
        
        if (conversor.converterCSVParaBib(caminhoAbrirArquivos, nomesAbrirArquivos, caminhoSalvarArquivo, nomeSalvarArquivo)) {
            JOptionPane.showMessageDialog(null, "Sucesso!", "Conversão concluída", JOptionPane.INFORMATION_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(null, "Erro!", "Erro ao converter", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jBtnConverterActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnConverter;
    private javax.swing.JButton jBtnSalvar;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLbEtapa2;
    private javax.swing.JLabel jLbEtapa2Desc;
    private javax.swing.JLabel jLbEtapa3;
    private javax.swing.JLabel jLbEtapa3Desc;
    private javax.swing.JLabel jLbEtapa4;
    private javax.swing.JLabel jLbNomesArquivos;
    private javax.swing.JLabel jLbQuantidadeArquivos;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPnEtapa1;
    private javax.swing.JPanel jPnEtapa2;
    private javax.swing.JPanel jPnEtapa3;
    private javax.swing.JPanel jPnEtapa4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTbRelacaoNomes;
    private javax.swing.JTextField jTxtLocalArbirArquivos;
    private javax.swing.JTextField jTxtLocalSalvarArquivo;
    // End of variables declaration//GEN-END:variables

    private void popularTabela(List<String> relacaoNomes) {
        limparTabela();

        for (String nome : relacaoNomes) {
            this.modeloTabela.addRow(new Object[]{nome, ""});
        }
    }

    private void limparTabela() {
        while (this.modeloTabela.getRowCount() > 0) {
            this.modeloTabela.removeRow(0);
        }
    }

    private void habilitarEtapa2() {
        this.jTbRelacaoNomes.setEnabled(true);
        this.jLbEtapa2.setEnabled(true);
        this.jLbEtapa2Desc.setEnabled(true);
    }

    private void habilitarEtapa3() {
        this.jBtnSalvar.setEnabled(true);
        this.jLbEtapa3.setEnabled(true);
        this.jLbEtapa3Desc.setEnabled(true);
    }

    private void habilitarEtapa4() {
        this.jBtnConverter.setEnabled(true);
        this.jLbEtapa4.setEnabled(true);
    }
}
